Repository sonata-project/SonataDoctrinePhpcrAdminBundle, pull requests merged in 2019-01, with the labels that each got.

#521 support Symfony 4
  .gitignore
  .travis/before_script_test.local.sh
  .travis/before_script_test.sh
  UPGRADE-3.0.md
  composer.json
  docs/reference/document_tree.rst
  docs/reference/filter_field_definition.rst
  docs/reference/form_field_definition.rst
  docs/reference/installation.rst
  phpunit.xml.dist
  src/Admin/Admin.php
  src/Block/TreeBlockService.php
  src/Builder/FormContractor.php
  src/Builder/ListBuilder.php
  src/Builder/ShowBuilder.php
  src/Filter/StringFilter.php
  src/Form/Type/ChoiceFieldMaskType.php
  src/Form/Type/Filter/ChoiceType.php
  src/Guesser/FilterTypeGuesser.php
  src/Guesser/TypeGuesser.php
  src/Resources/config/doctrine_phpcr_form_types.xml
  src/Resources/config/tree.xml
  tests/Fixtures/App/Admin/ContentAdmin.php
  tests/Fixtures/App/DataFixtures/Phpcr/LoadTreeData.php
  tests/Fixtures/App/Document/Content.php
  tests/Fixtures/App/Kernel.php
  tests/Fixtures/App/config/admin-test.xml
  tests/Fixtures/App/config/bundles.php
  tests/Fixtures/App/config/config.php
  tests/Fixtures/App/config/routing.php
  tests/Fixtures/App/config/routing.yml
  tests/Fixtures/App/config/sonata_phpcr_admin.yml
  tests/Fixtures/App/config/tree_browser_2.x.yml
  tests/Resources/Admin/ContentAdmin.php
  tests/Resources/app/AppKernel.php
  tests/Unit/Builder/ListBuilderTest.php
  tests/Unit/Datagrid/PagerTest.php
  tests/Unit/Datagrid/ProxyQueryTest.php
  tests/Unit/Filter/BaseTestCase.php
  tests/Unit/Guesser/FilterTypeGuesserTest.php
  tests/Unit/Route/PathInfoBuilderSlashesTest.php
  tests/WebTest/Admin/ContentAdminTest.php
  tests/WebTest/Dashboard/TreeBrowserTest.php
Labels: minor

#545 [Docs] big cleanup
  docs/reference/configuration.rst
  docs/reference/document_tree.rst
  docs/reference/filter_field_definition.rst
  docs/reference/form_field_definition.rst
  docs/reference/installation.rst
Labels: docs

#535 PHP 7.1 cleanups
  .travis/before_install_test.sh
  src/Filter/BooleanFilter.php
  tests/Fixtures/App/DataFixtures/Phpcr/LoadTreeData.php
  tests/Fixtures/App/Document/Content.php
  tests/Fixtures/App/config/bundles.php
  tests/Unit/Admin/AdminTest.php
  tests/Unit/Builder/ListBuilderTest.php
  tests/Unit/Datagrid/PagerTest.php
  tests/Unit/Datagrid/ProxyQueryTest.php
  tests/Unit/DependencyInjection/SonataDoctrinePHPCRAdminExtensionTest.php
  tests/Unit/Filter/BaseTestCase.php
  tests/Unit/Filter/BooleanFilterTest.php
  tests/Unit/Filter/CallBackFilterTest.php
  tests/Unit/Filter/ChoiceFilterTest.php
  tests/Unit/Filter/DateFilterTest.php
  tests/Unit/Filter/NodeNameFilterTest.php
  tests/Unit/Filter/NumberFilterTest.php
  tests/Unit/Filter/StringFilterTest.php
  tests/Unit/Guesser/FilterTypeGuesserTest.php
  tests/Unit/Route/PathInfoBuilderSlashesTest.php
  tests/WebTest/Admin/ContentAdminTest.php
  tests/WebTest/Dashboard/TreeBrowserTest.php
Labels: pedantic
