Repository sonata-project/SonataDoctrinePhpcrAdminBundle, pull requests merged in 2020-03, with the labels that each got.

#582 Fix missing missing parameter extension test
  tests/Unit/DependencyInjection/SonataDoctrinePHPCRAdminExtensionTest.php
Labels: pedantic

#583 Revert "Fix missing missing parameter extension test"
  tests/Unit/DependencyInjection/SonataDoctrinePHPCRAdminExtensionTest.php
Labels: pedantic

#584 Allow custom sortOrder
  src/Datagrid/ProxyQuery.php
  tests/Unit/Datagrid/ProxyQueryTest.php
Labels: minor

#586 Remove all special case for ChoiceFilter
  src/Filter/ChoiceFilter.php
  tests/Unit/Filter/ChoiceFilterTest.php
Labels: major

#587 Stop using default SortBy
  composer.json
  src/Model/ModelManager.php
Labels: major
